(load "1.21.scm")
(define (prime? x) (= x (smallest-divisor x)))
(define (timed-prime-test n)
    (newline)
      (display n)
        (start-prime-test n (current-milliseconds)))
(define (start-prime-test n start-time)
    (if (prime? n)
            (report-prime (- (current-milliseconds) start-time))))
(define (report-prime elapsed-time)
    (display " *** ")
    (display elapsed-time)
    (display "\n"))
; alias for timed-prime-test for interactive use
(define t timed-prime-test)
