; Exercise 1.9.
; Each of the following two procedures defines a method for
; adding two positive integers in terms of the procedures inc, which increments
; its argument by 1, and dec, which decrements its argument by 1.

(define (dec x) (- x 1))

(define (inc x) (+ x 1))

(define (add1 a b)
  (if (= a 0)
      b
      (inc (add1 (dec a) b))))

(define (add2 a b)
  (if (= a 0)
      b
      (add2 (dec a) (inc b))))

; Using the substitution model, illustrate the process generated by each
; procedure in evaluating (+ 4 5). Are these processes iterative or recursive?


; add1 is recursive; it builds up a stack of calls to inc, so the program state
; cannot be determined by only knowing the arguments to add1.
;
; add2 is iterative; it does not have a deferred stack.  Any call to add2 is
; going to have enough inforation to evaluate the answer.
